### ISSUE TITLE
Multiple upload at once ?

### ISSUE THREAD

**Issue by craftpip** [banago/Bridge#4]
Is there a way to upload multiple files at once using bridge ?

**Comment by banago** [comment]
@craftpip there is not a way to do that as far as I can remember. Would you like to work on something like that? On FTP is not possible at all I think, from previous research I've done on the topic.

**Comment by craftpip** [comment]
@banago, i have a need to upload multiple files, basically to queue up the files and update a specific number of files at once. This isn't possible by using command-line php functions, 
I'm working on it to find a way.
Thanks for your input, Appreciated.
