### ISSUE TITLE
Operation Timeout

### ISSUE THREAD

**Issue by craftpip** [banago/Bridge#6]
Is there a option to set a timeout for an operation performed ?
Thank you.

**Comment by banago** [comment]
Not right now,  but it will be possible in PHPloy 4.0. Why would you need to set an timeout? In what situations?

**Comment by craftpip** [comment]
because at time of incorrect server settings, Bridge takes a lot time trying to connect,
At the moment i added the timeout parameter in Bridge, but apparently timeout is not available for sftp connections
